version: '3.8'

services:
  app:
    build: .
    ports:
      - "5100:5100"
    environment:
      - PORT=5100
      - WEATHER_API_KEY=V3KRKFT57KX5KGE7AUMDRFAM4
      - CACHE_TTL_SECONDS=28800
    depends_on:
      - redis
    networks:
      - weather-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - weather-net

networks:
  weather-net:
